### ISSUE TITLE
Please, update the extension when Apple will release the official version of macOS Sierra

### ISSUE THREAD

**Issue by gusbemacbe** [mcs07/KeySearch#3]
I'm a developer and contributor of beta versions of Apple OSes for finding bugs and sending feedbacks.

I found the bugs in the extension of KeySearch:

1) The keywords list is empty;
2) Impossible to add new keyword;
3) Impossible to import and to export;
4) When you create and save the new keyword, you are open in a new tab of Safari;
5) There's no folder `~/Library/Application Support/Keywurl`. 

Please, fix these bugs when Apple will release the official version of macOS. You can fix the bugs and update the extension while macOS Sierra is still in beta, only if you want.

**Comment by edrozenberg** [comment]
Would be great to see this Sierra fix! I'm having the same issues. Existing keywords continue to work luckily, but am not able to edit or add new keywords configure anything else.

**Comment by behdad-keynejad** [comment]
Last commit is 4 years ago, I'm not sure if KeySearch is still being actively maintained by original developers. Maybe one of us should do the work. I'll look into the code tomorrow, see if I can do anything.

**Comment by mcs07** [comment]
Sorry, I do plan to fix this at the weekend. But any pull requests are welcome!

**Comment by Thunderforge** [comment]
KeySearch also has these problems on OS 10.11 (El Capitan) if it is running Safari 10. I will be happy to test future versions on this version if needed.

**Comment by edrozenberg** [comment]
I don't know where to start trying to fix the issues on Sierra. If anybody has a suggestion where to start I can take a look.

**Comment by gusbemacbe** [comment]
@edrozenberg 

You can clone it and analyse the faults in the package which you run on Safari extension developer tools. Contribute with its author.

**Comment by mcs07** [comment]
Hi everyone - this should now be fixed in version 2.1.3. Sorry for the delay. Let me know if you encounter any remaining problems.

**Comment by gusbemacbe** [comment]
KeySearch failed to parse JSON when I tried to import my keywords backup. I also didn't find the folder Keywurl in `~/Library/Application Support/`.

```
[
    {
        "keyword": "amazon",
        "name": "Amazon",
        "url": "http://www.amazon.com/s/ref=nb_sb_noss?field-keywords=@@@&url=search-alias%3Daps&tag=moxt-20",
        "enabled": true,
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wiktit",
        "name": "Wiktionary Italiano",
        "url": "https://it.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bennl",
        "name": "Babla English-Dutch",
        "url": "http://en.bab.la/dictionary/english-dutch/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgebfr",
        "name": "DDG Belgique",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=fr_BE&kah=wt-wt&kl=be-fr",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgit",
        "name": "DDG Italia",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=it_IT&kah=wt-wt&kl=it-it",
        "shortcut": ""
    },
    {
        "keyword": "image",
        "name": "Google Images",
        "url": "http://www.google.com/images?q=@@@",
        "enabled": true,
        "shortcut": ""
    },
    {
        "keyword": "wiki",
        "name": "Wikipedia",
        "url": "http://en.wikipedia.org/w/index.php?search=@@@",
        "enabled": true,
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikipt",
        "name": "Wikipedia Português",
        "url": "http://pt.wikipedia.org/w/index.php?search=@@@",
        "shortcut": "1001087"
    },
    {
        "enabled": true,
        "keyword": "wiktnl",
        "name": "Wiktionary Nederlands",
        "url": "https://nl.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gguk",
        "name": "Google United Kingdom",
        "url": "https://www.google.co.uk/#q=@@@&tbs=ctr:countryUK%7CcountryGB&cr=countryUK%7CcountryGB",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bpten",
        "name": "Babla Portuguese-English",
        "url": "http://en.bab.la/dictionary/portuguese-english/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "git",
        "name": "Google Italia",
        "url": "https://www.google.it/search?q=@@@&hl=it&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryIT&hl=it&tbs=ctr:countryIT,lr:lang_1it&lr=lang_it",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bnlen",
        "name": "Babla Dutch-English",
        "url": "http://en.bab.la/dictionary/dutch-english/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "guk",
        "name": "Google Україна",
        "url": "https://www.google.com.ua/#q=@@@&cr=countryUA&tbs=ctr:countryUA,lr:lang_1uk&lr=lang_uk",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bden",
        "name": "Babla German-English",
        "url": "http://en.bab.la/dictionary/german-english/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgenl",
        "name": "DDG Nederland",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=nl_NL&kah=wt-wt&kl=nl-nl",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "benpt",
        "name": "Babla English-Portuguese",
        "url": "http://en.bab.la/dictionary/english-portuguese/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ggus",
        "name": "Google United States",
        "url": "https://www.google.com/search?q=@@@&hl=en_US&ei=PAaiVL3FM8GngwSQ64HIAw",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wiktde",
        "name": "Wiktionary Deutsch",
        "url": "https://de.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wika”,
        "name": “ვიქსიკონი ქართული”,
        "url": "https://ka.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gfr",
        "name": "Google France",
        "url": "https://www.google.fr/search?q=@@@&hl=fr&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryFR&hl=fr&tbs=ctr:countryFR,lr:lang_1fr&lr=lang_fr",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gguy",
        "name": "Google Uruguay",
        "url": "https://www.google.com.uy/#q=@@@&cr=countryUY&tbs=ctr:countryUY,lr:lang_1es&lr=lang_es",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikro",
        "name": "Wikipedia Romănâ",
        "url": "http://pt.wikipedia.org/w/index.php?search=@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikies",
        "name": "Wikipedia Español",
        "url": "http://es.wikipedia.org/w/index.php?search=@@@",
        "shortcut": "1001087"
    },
    {
        "enabled": true,
        "keyword": "hds",
        "name": "Handspeak",
        "url": "http://www.handspeak.com/word/search.php?wordID=@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gde",
        "name": "Google Deutschland",
        "url": "https://www.google.de/#q=@@@&cr=countryDE&tbs=ctr:countryDE,lr:lang_1de&lr=lang_de",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikifr",
        "name": "Wikipedia Français",
        "url": "http://fr.wikipedia.org/w/index.php?search=@@@",
        "shortcut": "1001087"
    },
    {
        "enabled": true,
        "keyword": “tiger”,
        "name": “Translate Georgian“,
        "url": "http://www.translate.ge/?#search/@@@“,
        "shortcut": "1001087"
    },
    {
        "enabled": true,
        "keyword": "gar",
        "name": "Google Argentina",
        "url": "https://www.google.com.ar/#q=@@@&cr=countryAR&tbs=ctr:countryAR,lr:lang_1es&lr=lang_es",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgpt",
        "name": "DDG Portugal",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=pt_PT&kah=wt-wt&kl=pt-pt",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gru",
        "name": "Google Россия",
        "url": "https://www.google.ru/#q=@@@&cr=countryRU&tbs=ctr:countryRU,lr:lang_1ru&lr=lang_ru",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "vde",
        "name": "Verbformen",
        "url": "http://www.verbformen.net/conjugation/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gebarenl",
        "name": "NGT",
        "url": "https://www.lerengebaren.nl/gebarenwoordenboek/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bende",
        "name": "Babla English-German",
        "url": "http://en.bab.la/dictionary/english-german/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddguk",
        "name": "DDG UK",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=en_UK&kah=wt-wt&kl=uk-en",
        "shortcut": ""
    },
    {
        "keyword": "youtube",
        "name": "YouTube",
        "url": "http://www.youtube.com/results?search_query=@@@",
        "enabled": true,
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wiktpt",
        "name": "Wiktionary Português",
        "url": "https://pt.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wiktro",
        "name": "Wiktionary Romănâ",
        "url": "https://ro.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "dicin",
        "name": "Dicionário Informal",
        "url": "http://dicionarioinformal.com.br/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ggbr",
        "name": "Google Brasil",
        "url": "https://www.google.com.br/search?q=@@@&hl=pt_BR&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryBR&safe=off&hl=pt_BR&tbs=ctr:countryBR,lr:lang_1pt&lr=lang_pt",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgde",
        "name": "DDG Deutschland",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=de_DE&kah=wt-wt&kl=de-de",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gpt",
        "name": "Google Portugal",
        "url": "https://www.google.pt/search?q=@@@&hl=pt_PT&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryPT&hl=pt_PT&tbs=ctr:countryPT,lr:lang_1pt&lr=lang_pt",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "bfren",
        "name": "Babla French-English",
        "url": "http://en.bab.la/dictionary/french-english/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "fb",
        "name": "Facebook",
        "url": "https://www.facebook.com/search.php?q=@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikiit",
        "name": "Wikipedia Italiano",
        "url": "http://it.wikipedia.org/w/index.php?search=@@@",
        "shortcut": "1001087"
    },
    {
        "enabled": true,
        "keyword": "wiktru",
        "name": "Wiktionary Русский",
        "url": "https://ru.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wiktes",
        "name": "Wiktionary Español",
        "url": "https://es.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "vbxnl",
        "name": "Verbix Nederlands",
        "url": "http://www.verbix.com/webverbix/Dutch/@@@.html",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgbr",
        "name": "DDG Brasil",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=pt_BR&kah=wt-wt&kl=br-pt",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "priberam",
        "name": "Priberam",
        "url": "http://priberam.pt/dlpo/@@@",
        "shortcut": "1100080"
    },
    {
        "enabled": true,
        "keyword": "wiktfr",
        "name": "Wiktionary Français",
        "url": "https://fr.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "gmail",
        "name": "Gmail",
        "url": "https://mail.google.com/mail/?shva=1#search/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikt",
        "name": "Wiktionary",
        "url": "https://en.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "benfr",
        "name": "Babla English-French",
        "url": "http://en.bab.la/dictionary/english-french/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgebnl",
        "name": "DDG België",
        "url": " https://duckduckgo.com/?q=@@@&kae=t&kad=nl_BE&kah=wt-wt&kl=be-nl",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikja",
        "name": "Wiktionary 日本語",
        "url": "http://ja.wiktionary.org/wiki/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ges",
        "name": "Google España",
        "url": "https://www.google.es/search?q=@@@&hl=es_ES&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryES&hl=es_ES&tbs=ctr:countryES,lr:lang_1es&lr=lang_es",
        "shortcut": ""
    },
    {
        "enabled": false,
        "keyword": "default",
        "name": "default",
        "url": "http://www.google.com/search?q=@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikinl",
        "name": "Wikipedia Nederlands",
        "url": "http://nl.wikipedia.org/w/index.php?search=@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "woorden",
        "name": "Woorden",
        "url": "http://www.woorden.org/woord/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddges",
        "name": "DDG España",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=es_ES&kah=wt-wt&kl=es-es",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "ddgfr",
        "name": "DDG France",
        "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=fr_FR&kah=wt-wt&kl=fr-fr",
        "shortcut": ""
    },
    {
        "keyword": "map",
        "name": "Google Maps",
        "url": "http://maps.google.com/maps?q=@@@",
        "enabled": true,
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "myfonts",
        "name": "MyFonts",
        "url": "http://www.myfonts.com/search/@@@",
        "shortcut": ""
    },
    {
        "enabled": true,
        "keyword": "wikide",
        "name": "Wikipedia Deutsch",
        "url": "http://de.wikipedia.org/w/index.php?search=@@@",
        "shortcut": ""
    }
]
```

**Comment by mcs07** [comment]
It looks like some of the quote characters in your export have been converted to "curly quotes" - some text editors (I think TextEdit) do this.

Also, make sure you have set "KeySearch" on the import form, not "Keywurl" - that is another tool.

This should work:

    [
        {
            "keyword": "amazon",
            "name": "Amazon",
            "url": "http://www.amazon.com/s/ref=nb_sb_noss?field-keywords=@@@&url=search-alias%3Daps&tag=moxt-20",
            "enabled": true,
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wiktit",
            "name": "Wiktionary Italiano",
            "url": "https://it.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bennl",
            "name": "Babla English-Dutch",
            "url": "http://en.bab.la/dictionary/english-dutch/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgebfr",
            "name": "DDG Belgique",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=fr_BE&kah=wt-wt&kl=be-fr",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgit",
            "name": "DDG Italia",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=it_IT&kah=wt-wt&kl=it-it",
            "shortcut": ""
        },
        {
            "keyword": "image",
            "name": "Google Images",
            "url": "http://www.google.com/images?q=@@@",
            "enabled": true,
            "shortcut": ""
        },
        {
            "keyword": "wiki",
            "name": "Wikipedia",
            "url": "http://en.wikipedia.org/w/index.php?search=@@@",
            "enabled": true,
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikipt",
            "name": "Wikipedia Português",
            "url": "http://pt.wikipedia.org/w/index.php?search=@@@",
            "shortcut": "1001087"
        },
        {
            "enabled": true,
            "keyword": "wiktnl",
            "name": "Wiktionary Nederlands",
            "url": "https://nl.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gguk",
            "name": "Google United Kingdom",
            "url": "https://www.google.co.uk/#q=@@@&tbs=ctr:countryUK%7CcountryGB&cr=countryUK%7CcountryGB",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bpten",
            "name": "Babla Portuguese-English",
            "url": "http://en.bab.la/dictionary/portuguese-english/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "git",
            "name": "Google Italia",
            "url": "https://www.google.it/search?q=@@@&hl=it&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryIT&hl=it&tbs=ctr:countryIT,lr:lang_1it&lr=lang_it",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bnlen",
            "name": "Babla Dutch-English",
            "url": "http://en.bab.la/dictionary/dutch-english/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "guk",
            "name": "Google Україна",
            "url": "https://www.google.com.ua/#q=@@@&cr=countryUA&tbs=ctr:countryUA,lr:lang_1uk&lr=lang_uk",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bden",
            "name": "Babla German-English",
            "url": "http://en.bab.la/dictionary/german-english/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgenl",
            "name": "DDG Nederland",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=nl_NL&kah=wt-wt&kl=nl-nl",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "benpt",
            "name": "Babla English-Portuguese",
            "url": "http://en.bab.la/dictionary/english-portuguese/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ggus",
            "name": "Google United States",
            "url": "https://www.google.com/search?q=@@@&hl=en_US&ei=PAaiVL3FM8GngwSQ64HIAw",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wiktde",
            "name": "Wiktionary Deutsch",
            "url": "https://de.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wika",
            "name": "ვიქსიკონი ქართული",
            "url": "https://ka.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gfr",
            "name": "Google France",
            "url": "https://www.google.fr/search?q=@@@&hl=fr&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryFR&hl=fr&tbs=ctr:countryFR,lr:lang_1fr&lr=lang_fr",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gguy",
            "name": "Google Uruguay",
            "url": "https://www.google.com.uy/#q=@@@&cr=countryUY&tbs=ctr:countryUY,lr:lang_1es&lr=lang_es",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikro",
            "name": "Wikipedia Romănâ",
            "url": "http://pt.wikipedia.org/w/index.php?search=@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikies",
            "name": "Wikipedia Español",
            "url": "http://es.wikipedia.org/w/index.php?search=@@@",
            "shortcut": "1001087"
        },
        {
            "enabled": true,
            "keyword": "hds",
            "name": "Handspeak",
            "url": "http://www.handspeak.com/word/search.php?wordID=@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gde",
            "name": "Google Deutschland",
            "url": "https://www.google.de/#q=@@@&cr=countryDE&tbs=ctr:countryDE,lr:lang_1de&lr=lang_de",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikifr",
            "name": "Wikipedia Français",
            "url": "http://fr.wikipedia.org/w/index.php?search=@@@",
            "shortcut": "1001087"
        },
        {
            "enabled": true,
            "keyword": "tiger",
            "name": "Translate Georgian",
            "url": "http://www.translate.ge/?#search/@@@",
            "shortcut": "1001087"
        },
        {
            "enabled": true,
            "keyword": "gar",
            "name": "Google Argentina",
            "url": "https://www.google.com.ar/#q=@@@&cr=countryAR&tbs=ctr:countryAR,lr:lang_1es&lr=lang_es",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgpt",
            "name": "DDG Portugal",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=pt_PT&kah=wt-wt&kl=pt-pt",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gru",
            "name": "Google Россия",
            "url": "https://www.google.ru/#q=@@@&cr=countryRU&tbs=ctr:countryRU,lr:lang_1ru&lr=lang_ru",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "vde",
            "name": "Verbformen",
            "url": "http://www.verbformen.net/conjugation/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gebarenl",
            "name": "NGT",
            "url": "https://www.lerengebaren.nl/gebarenwoordenboek/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bende",
            "name": "Babla English-German",
            "url": "http://en.bab.la/dictionary/english-german/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddguk",
            "name": "DDG UK",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=en_UK&kah=wt-wt&kl=uk-en",
            "shortcut": ""
        },
        {
            "keyword": "youtube",
            "name": "YouTube",
            "url": "http://www.youtube.com/results?search_query=@@@",
            "enabled": true,
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wiktpt",
            "name": "Wiktionary Português",
            "url": "https://pt.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wiktro",
            "name": "Wiktionary Romănâ",
            "url": "https://ro.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "dicin",
            "name": "Dicionário Informal",
            "url": "http://dicionarioinformal.com.br/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ggbr",
            "name": "Google Brasil",
            "url": "https://www.google.com.br/search?q=@@@&hl=pt_BR&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryBR&safe=off&hl=pt_BR&tbs=ctr:countryBR,lr:lang_1pt&lr=lang_pt",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgde",
            "name": "DDG Deutschland",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=de_DE&kah=wt-wt&kl=de-de",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gpt",
            "name": "Google Portugal",
            "url": "https://www.google.pt/search?q=@@@&hl=pt_PT&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryPT&hl=pt_PT&tbs=ctr:countryPT,lr:lang_1pt&lr=lang_pt",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "bfren",
            "name": "Babla French-English",
            "url": "http://en.bab.la/dictionary/french-english/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "fb",
            "name": "Facebook",
            "url": "https://www.facebook.com/search.php?q=@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikiit",
            "name": "Wikipedia Italiano",
            "url": "http://it.wikipedia.org/w/index.php?search=@@@",
            "shortcut": "1001087"
        },
        {
            "enabled": true,
            "keyword": "wiktru",
            "name": "Wiktionary Русский",
            "url": "https://ru.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wiktes",
            "name": "Wiktionary Español",
            "url": "https://es.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "vbxnl",
            "name": "Verbix Nederlands",
            "url": "http://www.verbix.com/webverbix/Dutch/@@@.html",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgbr",
            "name": "DDG Brasil",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=pt_BR&kah=wt-wt&kl=br-pt",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "priberam",
            "name": "Priberam",
            "url": "http://priberam.pt/dlpo/@@@",
            "shortcut": "1100080"
        },
        {
            "enabled": true,
            "keyword": "wiktfr",
            "name": "Wiktionary Français",
            "url": "https://fr.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "gmail",
            "name": "Gmail",
            "url": "https://mail.google.com/mail/?shva=1#search/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikt",
            "name": "Wiktionary",
            "url": "https://en.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "benfr",
            "name": "Babla English-French",
            "url": "http://en.bab.la/dictionary/english-french/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgebnl",
            "name": "DDG België",
            "url": " https://duckduckgo.com/?q=@@@&kae=t&kad=nl_BE&kah=wt-wt&kl=be-nl",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikja",
            "name": "Wiktionary 日本語",
            "url": "http://ja.wiktionary.org/wiki/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ges",
            "name": "Google España",
            "url": "https://www.google.es/search?q=@@@&hl=es_ES&ie=utf-8&oe=utf-8&gws_rd=ssl&cr=countryES&hl=es_ES&tbs=ctr:countryES,lr:lang_1es&lr=lang_es",
            "shortcut": ""
        },
        {
            "enabled": false,
            "keyword": "default",
            "name": "default",
            "url": "http://www.google.com/search?q=@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikinl",
            "name": "Wikipedia Nederlands",
            "url": "http://nl.wikipedia.org/w/index.php?search=@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "woorden",
            "name": "Woorden",
            "url": "http://www.woorden.org/woord/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddges",
            "name": "DDG España",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=es_ES&kah=wt-wt&kl=es-es",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "ddgfr",
            "name": "DDG France",
            "url": "https://duckduckgo.com/?q=@@@&kae=t&kad=fr_FR&kah=wt-wt&kl=fr-fr",
            "shortcut": ""
        },
        {
            "keyword": "map",
            "name": "Google Maps",
            "url": "http://maps.google.com/maps?q=@@@",
            "enabled": true,
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "myfonts",
            "name": "MyFonts",
            "url": "http://www.myfonts.com/search/@@@",
            "shortcut": ""
        },
        {
            "enabled": true,
            "keyword": "wikide",
            "name": "Wikipedia Deutsch",
            "url": "http://de.wikipedia.org/w/index.php?search=@@@",
            "shortcut": ""
        }
    ]

**Comment by gusbemacbe** [comment]
It worked finally. Really it was the quote mark.

**Comment by edrozenberg** [comment]
2.1.3 is working fine for me, thanks a lot for the update!
